### ISSUE TITLE
"integrity check failed " 

### ISSUE THREAD

**Issue by acgacgacgacg** [livekit/livekit-server#591] opened 2022-04-05 13:24 UTC
@davidzhao @boks1971 @frostbyte73

## Bug report

I deployed a k8s cluster, and the [example](https://example.livekit.io/) web application works fine without server error.

The connection test is passed.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/10584507/161772203-15a1bd72-c47a-4e8a-8992-3ac7e18328ec.png">

However, when I used the flutter client sdk, the server gave the following error when connected.

```
2022-04-05T11:26:00.725Z        INFO    livekit rtc/room.go:225 new participant joined  {"room": "X8tGxiZ8jWlqLsEVzK1p", "roomID": "RM_PhMoAXQadoDE", "pID": "PA_K9oUjdYTFegz", "participant": "w44qrxPC2Ud2UVSGc7WbFMcW1ZX2", "protocol": 7, "options": {"AutoSubscribe":true}}
2022-04-05T11:26:00.981Z        ERROR   livekit.turn    v2@v2.0.8/server.go:184 error when handling datagram: failed to handle Allocate-request from 125.199.219.228:64247: integrity check failed
github.com/pion/turn/v2.(*Server).readLoop
        /go/pkg/mod/github.com/pion/turn/v2@v2.0.8/server.go:184
github.com/pion/turn/v2.NewServer.func1
        /go/pkg/mod/github.com/pion/turn/v2@v2.0.8/server.go:85
```

I connected the server using the sample code like below

```dart
room = await LiveKitClient.connect(
          LIVEKIT_SERVER,
          _token,
          roomOptions: options,
        );
```

client sdk version: 0.5.8
server version: 0.15.5

Would you please help me to solve this problem ?
I have been stuck in this for 3 days.

**Comment by davidzhao** [comment] 2022-04-06 07:08
Duplicate of https://github.com/livekit/client-sdk-flutter/issues/102.

Hi @acgacgacgacg, we'll take a look, but I'd like to ask you to avoid filing duplicate issues as this increases our workload.

**Closed by davidzhao** 2022-04-06 07:08 UTC

**Comment by acgacgacgacg** [comment] 2022-04-06 08:31
@davidzhao 
Thanks ! I won't fill duplicated issue.

Additional information:
When `localParticipant.setMicrophoneEnabled(true)` fired,
the `integrity check failed` error will also occur, that's why there are two of this error after room connected.
